name: BlockClaims
description: Adds a block claiming system to Pocketmine!
author: BalAnce
version: 0.5
main: blockclaims\main
api: 1.12.0
commands:
 claim:
  description: Main BlockClaims management Command!